config/routes.rb
Rails.application.routes.draw do
  
# static_pagesコントローラー
  # ルートページ
  root 'static_pages#home'
  
# usersコントローラー
  # 新規作成画面へ 
  get '/signup',    to: 'users#new'
  # 基本情報編集画面へ (/edit-basic-info/1という形式のURLでGETリクエストが送信出来るようになる)
  # このURLの記法だと_pathヘルパーが作成されないので、asオプションを使用することでbasic_info_pathメソッドが生成する
  get '/edit-basic-info', to: 'users#edit_basic_info', as: :basic_info 
  # 基本情報編集画面の更新処理
  patch 'update-basic-info', to: 'users#update_basic_info'
  
# sessionsコントローラー
  # ログイン画面へ
  get    '/login',  to: 'sessions#new'
  # セッションを作成&保存(ログイン状態になる)
  post   '/login',  to: 'sessions#create'
  # ログイン状態を破棄
  delete '/logout', to: 'sessions#destroy'
  
# users > attendancesコントローラー
  # 勤怠編集画面へ ( 何年何月の勤怠表示画面から遷移したかも判定し、編集画面の１ヶ月分の表示を合わせる必要があるため:dateを入れる )
  get 'user/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances
  # 勤怠編集の更新
  patch 'user/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  
# basesコントローラー
  # # 拠点情報ページへ
  # get 'bases/index', to: 'bases#index'
  # # 拠点情報の追加ページ
  # get 'bases/new', to: 'bases#new'
  # # 拠点情報の新規作成
  # post 'bases/create', to: 'bases#create', as: :bases
  # # 拠点情報の編集ページ
  # get 'bases/:id/edit', to: 'bases#edit', as: :edit_base
  # # 拠点情報の更新
  # patch 'bases/:id', to: 'bases#update', as: :base
  # # 拠点情報の削除
  # delete 'bases/:id', to: 'bases#destroy'
  
# baseリソース
  resources :bases do
  end
  
# usersリソース
  resources :users do

    
    member do
      patch  'update_index', as: :update_index # ユーザ一覧の更新
      get 'attendance_log', as: :attendance_log # 勤怠修正ログページ
    end
    
    # 勤怠情報を保存する
    resources :attendances, only: :create #リソースをネストしていることで/users/:user_id/attendanceというURLになる。
    
  end
  
  resources :attendances do
    collection do
      get 'attendance_list', as: :attendance_list # 出勤社員一覧ページ
      get 'csv_output', as: :csv_output # csv出力アクション
    end
    
    member do
      patch 'update_attendance_info', as: :update_attendance_info # 勤怠変更お知らせの更新
      patch 'update_overtime', as: :update_overtime # 残業申請
      patch 'update_overtime_info', as: :update_overtime_info # 残業申請お知らせの更新
      patch 'update_month', as: :update_month # １ヶ月分の勤怠申請
      patch 'update_month_info', as: :update_month_info # １ヶ月分の勤怠申請お知らせの更新
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
# 1対多の関連性を示す。又、ユーザーが削除された時に関連する勤怠情報も同様に削除されるよう設定している
  has_many :attendances, dependent: :destroy
# コールバックメソッド 保存される前に現在のメールアドレスの値を小文字にする。又、selfは現在のユーザーを指している
  before_save { self.email = email.downcase }
# nameカラムの存在性と最大文字数を検証
  validates :name, presence: true, length: { maximum: 50}
# メールアドレスのフォーマットを検証できる
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
# emailカラムの存在性と最大文字数、フォーマット、一意性を検証(indexを追加してデータベースレベルでも一意性を強制する)
  validates :email, presence: true, length: { maximum: 100}, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
# password_digestカラムとbcrpt gemを追加したことで使用可能になった
  has_secure_password
# パスワードの存在性と最小文字数の検証、allow_nilでパスワードを入力していない場合は検証をスルーして更新
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
# departmentカラムの文字数検証は範囲を指定するオプションinを使用、空でも通るようにallow_nil
  validates :department, length: {in: 3..50}, allow_blank: true
# user.remember_tokenでトークンにアクセス出来るように、かつトークンをデータベースに保存せずに実装する必要があるため
# attr_accessorを使ってアクセス可能な属性を作成している
  attr_accessor :remember_token
  
  
  # 上長一覧(自分が上長の場合、自分を除く)
  def User.superior_user_list_non_self(session)
    if User.find(session[:user_id]).superior == true
      where(superior: true).where.not(id: session[:user_id])
    else
      where(superior: true)
    end
  end
  
  
  # remember
  
  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64 # SecureRandomモジュールにあるurlsafe_base64メソッド（ランダムな文字64種から22字の字列を作成）
  end
  
  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token #selfキーワードを与えると、この代入によってユーザーのremember_token属性が期待どおりに設定される
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil? # authenticated?を更新して、ダイジェストが存在しない場合に対応
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # ログイン済みでなければ実行できない
  before_action :logged_in_user, only: [:index, :edit, :update]
  # 正しいユーザーでなければ実行できない
  before_action :correct_user,   only: [:edit]
  # 管理者でなければ実行できない
  before_action :admin_user,     only: [:destroy, :edit_basic_info, :update_basic_info, :index, :update_index]
  # 管理者はNG
  before_action :not_admin_user, only: [:show, :edit]
  before_action :superior_user, only: [:show]
  
  # ユーザー一覧ページ
  def index
    # @users = User.paginate(page: params[:page]) # paginateメソッドの働きで、ユーザーのページネーションが行えるようになる。paramsの:pageはビューに記述したwill_paginateで自動生成される
    @users = User.all
  end
  
  # ユーザ一覧　編集して更新(管理者のみ)
  def update_index
    @user = User.find(params[:id])
    if @user.update_attributes(users_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to users_url
    else
      render 'edit'
    end
  end
  
  # ユーザー勤怠画面
  def show
    @user = User.find(params[:id])
    # debugger  # インスタンス変数を定義した直後にこのメソッドが実行される
    # attendanceヘルパーメソッド使用
    @first_day = first_day(params[:first_day])
    @last_day = @first_day.end_of_month # 初月の日付を使って月末をインスタンス変数に代入
    @week = %w{日 月 火 水 木 金 土} # 曜日を配列に代入
    (@first_day..@last_day).each do |day|
      # any?メソッドは、ブロック変数attendanceに要素を入れながらブロック（ここではattendance.worked_on == day）を実行し、
      # ブロックが真（true）を返した時は、ブロック実行をその時点で中断しtrueを返します。ブロックの戻り値が全て偽（false）である時はfalseが返されます
      unless @user.attendances.any? {|attendance| attendance.worked_on == day} # unless文なのでfalseの場合、下の処理をする。
        record = @user.attendances.build(worked_on: day) # Railsの慣習に倣い、あるモデルに関連づいたモデルのデータを生成するのにbuildメソッドを使っている
        record.save
      end
    end
    # orderメソッドは取得した値を特定のキーで並び替える。並び替えはデフォルトで昇順(ASC)
    @dates = user_attendances_month_date
    # 出勤日数の合計
    @worked_sum = @dates.where.not(started_at: nil).count
    # 残業モーダルのform用
    @attendance = @user.attendances.new
    # 勤怠変更申請のカウント
    @attendance_application_count = Attendance.where(attendance_order_id: current_user.name).count
    # 残業申請のカウント
    @overtime_application_count = Attendance.where(over_order_id: current_user.name).count
    # １ヶ月の勤怠申請のカウント
    @month_application_count = Attendance.where(month_order_id: current_user.name).count
  end
  
  # 新規登録ページ
  def new
    @user = User.new # 新規作成されたUserオブジェクトをインスタンス変数に代入する
  end
  
  # 新規登録作成
  def create
    # admin　ユーザー一覧からのCSVインポート
    if params[:commit] == "CSVをインポート"
      
      if params[:users_file].content_type == "text/csv" # file_field_tagで選択したファイルがCSVファイルかどうか
          registered_count = import_users # import_usersは下の方にメソッドあり CSVのインポート処理関連
          unless @errors.count == 0
            flash[:danger] = "#{@errors.count}件登録に失敗しました"
          end
          unless registered_count == 0
            flash[:success] = "#{registered_count}件登録しました"
          end
          redirect_to users_url(error_users: @errors)
      else
        flash[:danger] = "CSVファイルのみ有効です"
        redirect_to users_url
      end
    else
      @user = User.new(users_params) # Strong Parametersを用いる
      if @user.save
        log_in @user # 登録成功時にログインする
        flash[:success] = "ユーザーの新規作成に成功しました。"
        redirect_to @user # redirect_to user_url(@user)と同じ内容
      else
        render 'new'
      end
    end
  end
  
  # ユーザー編集ページ
  def edit
    # correct_userで定義したため削除していい
    # @user = User.find(params[:id])
  end
  
  # ユーザーの更新
  def update
    # correct_userで定義したため削除していい
    @user = User.find(params[:id])
    # update_attributesには引数としてuser_pramsを渡し、無効な情報だった場合はfalseが返ってくるのでそれを利用してif~else文を構築
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      if current_user.admin?
        redirect_to users_path
      else
        redirect_to @user
      end
    else
      render 'edit'
    end
  end
  
  # ユーザーの削除
  def destroy
    if current_user.admin?
      @user = User.find(params[:id])
      if @user.admin == true
        flash[:danger] = "管理者は削除できません。"
      else
        @user.destroy
        flash[:success] = "削除しました。"
      end
      
    else
      flash[:danger] = "管理者しか削除できません。"
    end
    redirect_to users_url
  end
  
  # 基本情報編集ページ
  def edit_basic_info
    # @user = User.find(params[:id])  
  end
  
  # 基本情報編集の更新
  # def update_basic_info
  #   @user = User.find(params[:id])
  #   if @user.update_attributes(basic_info_params)
  #     flash[:success] = "基本情報を更新しました。"
  #     redirect_to @user
  #   else
  #     render 'edit_basic_info'
  #   end
  # end
  
  # 勤怠修正ログページ
  def attendance_log
    @user = User.find(params[:id])
    # @attendance_logs = @user.attendances.where(attendance_order_id: "承認").order('worked_on')
    if params[:year]
      date = Date.new(params[:year].to_i, params[:month].to_i)
      @attendance_logs = @user.attendances.where(attendance_order_id: "承認").where(worked_on: date.beginning_of_month..date.end_of_month)
    else
      @attendance_logs = @user.attendances.where(attendance_order_id: "承認").where(worked_on: Time.now.beginning_of_month..Time.now.end_of_month)
    end
  end
  
  
  private
  
    # Strong Parameters 必須となるパラメータと許可されたパラメータを指定することができる。
    # ユーザー設定で使用
    def user_params
      params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
    end
    
    # 基本情報の更新で使用
    def basic_info_params
      params.require(:user).permit(:basic_time, :work_time)
    end
  
    # ユーザ一覧の更新で使用
    def users_params
      params.require(:user).permit(:name, :email, :department, :password, :password_confirmation, :code, :card_id, :surperior, :basic_time, :work_time, :work_time_finish)
    end
  
    # beforeアクション
    
    # ログイン済みユーザーか確認
    def logged_in_user
      unless logged_in?
        # sessionsヘルパーメソッド
        store_location
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
      end
    end

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      # 後付けif文の構成と一緒で、条件式がfalseの場合のみ、冒頭のコードが実行される、current_user?はsessonヘルパーメソッド
        redirect_to(root_url) unless current_user?(@user)
    end
    
    # 管理者かどうか確認
    def admin_user
      unless current_user.admin?
        flash[:danger] = "管理者権限がありません。"
        redirect_to(root_url)
      end
    end
    
    # 管理者はNG
    def not_admin_user
      redirect_to(root_url) if current_user.admin?
    end
    
    # 自分か上長か
    def superior_user
      @user = User.find(params[:id])
      @first_day = first_day(params[:first_day])
      unless current_user?(@user)
        unless current_user.superior?
          flash[:danger] = "閲覧権限がありません。"
          redirect_to user_path(id: current_user.id, finst_day: @first_day)
        else
          unless params[:first_day].present?
            redirect_to user_path(id: current_user.id, first_day: @first_day)
          end
        end
      end
    end
    
    # CSVインポート
    def import_users
      # 登録処理前のレコード数
      current_user_count = ::User.count
      users = []
      @errors = []
      # windowsで作られたファイルに対応するので、encoding: "SJIS"を付けている
      # headersオプションを使うと、CSVの初めの1行はheaderとして出力の際に無視される (nameなどの属性名部分)
      CSV.foreach(params[:users_file].path, headers: true) do |row| # CSV.foreach # ファイルから一行ずつ読み込み 又、application.rbでrequire 'csv'も必要
        user = User.new({ name: row["name"], email: row["email"], department: row["affiliation"], code: row["employee_number"], card_id: row["uid"], basic_time: row["basic_work_time"], 
                              work_time: row["designated_work_start_time"], work_time_finish: row["designated_work_end_time"], superior: row["superior"], admin: row["admin"], password: row["password"]})
        if user.valid?
            users << ::User.new({ name: row["name"], email: row["email"], department: row["affiliation"], code: row["employee_number"], card_id: row["uid"], basic_time: row["basic_work_time"], 
                              work_time: row["designated_work_start_time"], work_time_finish: row["designated_work_end_time"], superior: row["superior"], admin: row["admin"], password: row["password"]})
        else
          @errors << user.errors.inspect # inspectメソッドとは、オブジェクトや配列などをわかりやすく文字列で返してくれるメソッド
        end
      end
      # importメソッドでバルクインサートできる(gem 'activerecord-import'が必要)
      ::User.import(users)
      # 何レコード登録できたかを返す
      ::User.count - current_user_count
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
  # 基本時間などの値を、指定の書式にフォーマットして返す
  def format_basic_time(datetime)
    format("%.2f", ((datetime.hour * 60) + datetime.min)/60.0) # %.2f"は戻り値となる文字列書式を指定している
  end

end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>  <!-- 新規か既存オブジェクトかを確認し、新規ならPOST、既存ならPATCHリクエストが使われる -->
  <%= render 'shared/error_messages', object: @user %>   <!-- 登録失敗時のエラーメッセージ -->
  
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>
  
  <%= f.label :department %>
  <%= f.text_field :department, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %> <!-- 新規と更新で表示を変えるためyieldメソッドに引数を渡している -->
<% end %>

app/views/users/_log_table.html.erb
<table class="table-bordered table-condensed">
  <thead>
  <tr>
    <th>日付</th>
    <th>変更前出社時間</th>
    <th>変更前退社時間</th>
    <th>変更後出社時間</th>
    <th>変更後退社時間</th>
    <th>承認者</th>
    <th>承認日</th>
  </tr>
  </thead>
  
  <tbody id="relord">
    <% @attendance_logs.each do |log| %>
      <tr>
        <!-- 日付 -->
        <td><%= log.worked_on %></td>
        <!-- 変更前出社時間 -->
        <td><%= log.started_at.to_s(:time) if log.started_at.present? %></td>
        <!-- 変更前退社時間 -->
        <td><%= log.finished_at.to_s(:time) if log.started_at.present? %></td>
        <!-- 変更後出社時間 -->
        <td><%= log.started_at_after.to_s(:time) %></td>
        <!-- 変更後退社時間 -->
        <td><%= log.finished_at_after.to_s(:time) %></td>
        <!-- 承認者 -->
        <td><%= log.attendance_order_status %></td>
        <!-- 承認日 -->
        <td><%= log.approval_day %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_user.html.erb
<li>
  <!-- 現在のユーザーが管理者(admin属性がtrue)の場合に限り -->
  <!--< if current_user.admin? && !current_user?(user) %>-->

  <%= user.name %>
    <div>
      | <%= link_to "削除", user, method: :delete, data: {confirm: "削除してよろしいですか？"}, class: "btn btn-primary" %>
    </div>
  
    <div class="panel-group" id="accordion">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapse-<%= user.id %>" class="btn btn-a btn-primary">
              編集
            </a> <!-- user.idでアコーディオンを紐付け -->
          </h4>
        </div> <!-- panel-heading -->
          <div id="collapse-<%= user.id %>" class="panel-collapse collapse">
            <div class="panel-body">
              <%= form_for user, url: update_index_user_path(user), method: :patch do |f| %>
              <% @user = User.find(user.id) %>
              <%= render 'shared/error_messages' %>   <!-- 登録失敗時のエラーメッセージ -->
              
                <!-- 名前 -->
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>
  
                <!-- メールアドレス -->
                <%= f.label :email %>
                <%= f.email_field :email, class: 'form-control' %>
  
                <!-- 所属 -->
                <%= f.label :department %>
                <%= f.text_field :department, class: 'form-control' %>
  
                <!-- 社員番号 -->
                <%= f.label :code %>
                <%= f.text_field :code, class: 'form-control' %>
  
                <!-- カード番号 -->
                <%= f.label :card_id %>
                <%= f.text_field :card_id, class: 'form-control' %>
                
                <!-- パスワード -->
                <%= f.label :password %>
                <%= f.password_field :password, class: 'form-control' %>
  
                <!-- パスワード確認 -->
                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation, class: 'form-control' %>
  
                <!-- 基本勤務時間 -->
                <%= f.label :basic_time %>
                <%= f.time_field :basic_time, class: 'form-control' %>
  
                <!-- 指定勤務開始時間 -->
                <%= f.label :work_time %>
                <%= f.time_field :work_time, class: 'form-control' %>
  
                <!-- 指定勤務終了時間 -->
                <%= f.label :work_time_finish %>
                <%= f.time_field :work_time_finish, class: 'form-control' %>
  
                <%= f.submit '編集する', class: "btn btn-primary" %>
              <% end %>
            </div> <!-- panel-body -->
          </div> <!-- id="collapse -->
      </div> <!-- panel panel-default -->
    </div> <!-- panel-group -->
  <!--< end %> <!-- if current_user.admin? -->
</li>

app/views/users/edit.html.erb
<% provide(:title, "設定") %>
<% provide(:button_text, "更新する") %>

<h1>ユーザー情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<!--< provide(:title, "基本情報編集") %>-->

<!--<h1>基本情報の編集</h1>-->

<!--<div class="row">-->
<!--  <div class="col-md-6 col-md-offset-3">-->
<!--    <= form_for(@user, url: update_basic_info_path(params: {id: @user.id})) do |f| %>-->
<!--      <= render 'shared/error_messages', object: @user %>-->
      
<!--      <= f.label :basic_time %>-->
<!--      <= f.time_field :basic_time, class: 'form-control' %>-->

<!--      <= f.label :work_time %>-->
<!--      <= f.time_field :work_time, class: 'form-control' %>-->
      
<!--      <= f.submit "更新する", class: "btn btn-primary" %>-->
<!--    < end %>-->
<!--  </div>-->
<!--</div>-->

app/views/users/index.html.erb
<% provide(:title, '一覧') %>
<h1>ユーザ一覧</h1>

<%= form_tag users_path, method: :post, multipart: true do %> <!-- ファイル読み込みの際はmultipart:trueが必要 -->
  <div class="input-group" style="width: 300px;">
    <span class="input-group-btn">
      <!-- onclickはトリガー。この要素をクリックした時に、非表示にしているfile_field_tag(idから)に対してclickイベントを発生させている。
      つまり、ここをクリックすればfile_field_tagのボタンもクリックしたことになり、ファイル選択のダイアログが表示されるようになる。 -->
      <%= button_tag 'ファイル選択', class: "btn btn-default csv_input_btn", type: 'button', onclick: "$('#file_input').click();" %>
    </span>
    <!-- display: noneは非表示になっているだけで機能を無効化してるわけではない。又、required属性で入力を必須にしてエラーが出ないようにしている -->
    <%= file_field_tag 'users_file', id: "file_input", style: "display: none;", onchange: "file_selected($(this));" , required: "required" %>
    <%= text_field_tag 'filename',"", id: "filename", disabled: true, class:"form-control" %>
  </div>
  <br>
  <%= submit_tag 'CSVをインポート', style: "width: 300px", class: "btn btn-primary csv_submit" %>
<% end %>

<!-- ページネーションを動作させる -->
<!--<= will_paginate %>-->

<ul class="users">
  <!-- @users.each do |user| -->
     <!-- 引数のuserはブロック変数のuserを指している。この場合、Railsでは自動的に_user.html.erbを探してくれる。 -->
     <!-- render @users -->
  <!-- end --> <!-- eachメソッドすら省略したリファクタリングが下　-->
  
  <!-- Railsが自動的に@usersの値を評価し、それぞれのユーザーを_user.html.erbパーシャルで出力してくれる-->
  <%= render @users %>
  
</ul>

<!-- ページネーションを動作させる -->
<!--<= will_paginate %>-->

<!-- text_field_tagに選択したファイル名を表示させる -->
<script type="text/javascript">
  function file_selected(file_field){
    var filename = $(file_field)[0].files[0].name;
    $("#filename").val(filename);
  }
</script>

app/views/users/new.html.erb
<% provide(:title, 'ユーザー作成') %>
<% provide(:button_text, '作成する') %>

<h1>ユーザ新規作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>