config/routes.rb
Rails.application.routes.draw do
  
# static_pagesコントローラー
  # ルートページ
  root 'static_pages#home'
  
# usersコントローラー
  # 新規作成画面へ 
  get '/signup',    to: 'users#new'
  # 基本情報編集画面へ (/edit-basic-info/1という形式のURLでGETリクエストが送信出来るようになる)
  # このURLの記法だと_pathヘルパーが作成されないので、asオプションを使用することでbasic_info_pathメソッドが生成する
  get '/edit-basic-info', to: 'users#edit_basic_info', as: :basic_info 
  # 基本情報編集画面の更新処理
  patch 'update-basic-info', to: 'users#update_basic_info'
  
# sessionsコントローラー
  # ログイン画面へ
  get    '/login',  to: 'sessions#new'
  # セッションを作成&保存(ログイン状態になる)
  post   '/login',  to: 'sessions#create'
  # ログイン状態を破棄
  delete '/logout', to: 'sessions#destroy'
  
# users > attendancesコントローラー
  # 勤怠編集画面へ ( 何年何月の勤怠表示画面から遷移したかも判定し、編集画面の１ヶ月分の表示を合わせる必要があるため:dateを入れる )
  get 'user/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances
  # 勤怠編集の更新
  patch 'user/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  
# basesコントローラー
  # # 拠点情報ページへ
  # get 'bases/index', to: 'bases#index'
  # # 拠点情報の追加ページ
  # get 'bases/new', to: 'bases#new'
  # # 拠点情報の新規作成
  # post 'bases/create', to: 'bases#create', as: :bases
  # # 拠点情報の編集ページ
  # get 'bases/:id/edit', to: 'bases#edit', as: :edit_base
  # # 拠点情報の更新
  # patch 'bases/:id', to: 'bases#update', as: :base
  # # 拠点情報の削除
  # delete 'bases/:id', to: 'bases#destroy'
  
# baseリソース
  resources :bases do
  end
  
# usersリソース
  resources :users do

    
    member do
      patch  'update_index', as: :update_index # ユーザ一覧の更新
      get 'attendance_log', as: :attendance_log # 勤怠修正ログページ
    end
    
    # 勤怠情報を保存する
    resources :attendances, only: :create #リソースをネストしていることで/users/:user_id/attendanceというURLになる。
    
  end
  
  resources :attendances do
    collection do
      get 'attendance_list', as: :attendance_list # 出勤社員一覧ページ
      get 'csv_output', as: :csv_output # csv出力アクション
    end
    
    member do
      patch 'update_attendance_info', as: :update_attendance_info # 勤怠変更お知らせの更新
      patch 'update_overtime', as: :update_overtime # 残業申請
      patch 'update_overtime_info', as: :update_overtime_info # 残業申請お知らせの更新
      patch 'update_month', as: :update_month # １ヶ月分の勤怠申請
      patch 'update_month_info', as: :update_month_info # １ヶ月分の勤怠申請お知らせの更新
    end
  end

end

app/models/attendance.rb
class Attendance < ApplicationRecord
# 1対1の関連性を示す
  belongs_to :user

end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  # 管理者はNG
  before_action :not_admin_user, only: [:edit]
  # 管理者でなければ実行できない
  before_action :admin_user,     only: [:attendance_list]
  
  
  # 勤怠情報を更新
  def create
    @user = User.find(params[:user_id]) # /users/:user_id/attendancesの:user_idから、インスタンス変数@userを定義している。
    @attendance = @user.attendances.find_by(worked_on: Date.today) # 出勤時間を保存するためのレコードをattendancesテーブルから探し、インスタンス変数@attendanceに代入している。
    if @attendance.started_at.nil?
      @attendance.update_attributes(started_at: current_time) # attendanceヘルパーメソッドを使用
      flash[:info] = 'おはようございます。'
    elsif @attendance.finished_at.nil?
      @attendance.update_attributes(finished_at: current_time)
      flash[:info] = 'おつかれさまでした。'
    end
    redirect_to @user
  end
  
  # 勤怠編集画面
  def edit
    # ルーティングで割り当てたパラメータからそれぞれのインスタンス変数に値を代入できるように設定している。
    @user = User.find(params[:id])
    @first_day = first_day(params[:date])
    @last_day = @first_day.end_of_month
    @week = %w{日 月 火 水 木 金 土}
    @dates = user_attendances_month_date
  end

  # 勤怠編集の更新
  def update
    @user = User.find(params[:id])
    # attendanceヘルパーメソッドを使用
    if attendances_invalid?
      attendances_params.each do |key, value| # idと値
        attendance = Attendance.find(key) # idを使い更新対象となるAttendanceモデルのデータを取得
        if value[:attendance_order_id] == ""
          attendance.update_attributes(started_at: value[:started_at], finished_at: value[:finished_at],next_day: value[:next_day],
                                        note: value[:note], attendance_order_id: value[:attendance_order_id]) # 編集した値に更新する
                                        
        else
          attendance.update_attributes(started_at_after: value[:started_at], finished_at_after: value[:finished_at],next_day: value[:next_day],
                                        note: value[:note], attendance_order_id: value[:attendance_order_id]) # 編集した値に更新する
        end
      end
      flash[:success] = '勤怠情報を更新しました。'
      redirect_to user_url(@user, params:{first_day: params[:date]})
    else
      flash[:danger] ='不正な時間入力がありました、再入力してください。'
      redirect_to edit_attendances_path(@user, params[:date])
    end
  end
  
  # 勤怠変更お知らせの更新
  def update_attendance_info
    @user = User.find(params[:id])
    update_count = 0
    update_attendance_info_params.each do |id, item|
      if item[:agreement] == "true"
        attendance = Attendance.find(id)
        attendance.update_attributes(attendance_order_id: item[:attendance_order_id], attendance_order_status: current_user.name, approval_day: Date.today)
        update_count += 1
      end
    end
    flash[:success] = "#{update_attendance_info_params.keys.count}件中#{update_count}件の申請を更新しました。"
    redirect_to user_path(@user)
  end
  
  # 残業申請の申請
  def update_overtime
    @user = User.find(params[:id])
    @attendance = @user.attendances.find_by(worked_on: params[:attendance][:day])
    if @attendance.update_attributes(update_overtime_params)
      flash[:success] = "残業の申請をしました。"
      redirect_to @user
    end
  end
  
  # 残業申請お知らせの更新
  def update_overtime_info
    @user = User.find(params[:id])
    update_count = 0
    update_overtime_info_params.each do |id, item|
      if item[:agreement] == "true"
        attendance = Attendance.find(id)
        attendance.update_attributes(over_order_id: item[:over_order_id], over_order_status: current_user.name)
        update_count += 1
      end
    end
    flash[:success] = "#{update_overtime_info_params.keys.count}件中#{update_count}件の申請を更新しました。"
    redirect_to @user
  end
  
  # １ヶ月分の勤怠申請の申請
  def update_month
    @user = User.find(params[:id])
    day = params[:first_day]
    @attendance = @user.attendances.find_by(worked_on: day)
    unless params[:attendance][:month_order_id].empty? # 申請時、所属長選択が空の場合
      @attendance.update_attributes(update_month_params)
      flash[:success] = "１ヶ月の勤怠を申請をしました。"
    else
      flash[:danger] = "所属長を選択してください。"
    end
    redirect_to @user
  end
  
  # １ヶ月分の勤怠申請の更新
  def update_month_info
    @user = User.find(params[:id])
    update_count = 0
    update_month_info_params.each do |id, item|
      if item[:agreement] == "true"
        attendance = Attendance.find(id)
        attendance.update_attributes(month_order_id: item[:month_order_id], month_order_status: current_user.name, approval_day: Date.today)
        update_count += 1
      end
    end
    flash[:success] = "#{update_month_info_params.keys.count}件中#{update_count}件の申請を更新しました。"
    redirect_to @user
  end
  
  # 出勤社員一覧ページ
  def attendance_list
    # usersテーブルとattendancesテーブルの両方のテーブルの値を取得するため、includesメソッドを使用
    @users = User.all.includes(:attendances)
  end
  
  # csv出力
  def csv_output
    @user = User.find(current_user.id)
    @first_day = first_day(params[:first_day])
    @last_day = @first_day.end_of_month
    @attendances = user_attendances_month_date
    send_data render_to_string, filename: "#{@user.name}の勤怠情報.csv", type: :csv
  end
  
  
  private
    
    # 勤怠編集の更新で使用
    def attendances_params
      params.permit(attendances: [:started_at, :finished_at, :note, :next_day, :attendance_order_id])[:attendances]
    end
    
    # 勤怠変更お知らせの更新で使用
    def update_attendance_info_params
      params.permit(attendances: [:attendance_order_id, :agreement])[:attendances]
    end
    
    # 残業申請で使用
    def update_overtime_params
      params.require(:attendance).permit(:endplans_time, :next_day, :business_contents, :over_order_id)
    end
    
    # 残業申請お知らせの更新で使用
    def update_overtime_info_params
      params.permit(attendances: [:over_order_id, :agreement])[:attendances]
    end
    
    # １ヶ月分の勤怠申請で使用
    def update_month_params
      params.require(:attendance).permit(:month_order_id)
    end
    
    # １ヶ月分の勤怠申請お知らせの更新で使用
    def update_month_info_params
      params.permit(attendances: [:month_order_id, :agreement])[:attendances]
    end
    
    # 管理者かどうか確認
    def admin_user
      unless current_user.admin?
        flash[:danger] = "管理者権限がありません。"
        redirect_to(root_url)
      end
    end
    
    # 管理者はNG
    def not_admin_user
      redirect_to(root_url) if current_user.admin?
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  
  # 現在の時間を作成(started_atとfinished_atを作成するときに使用)
  def current_time
    Time.new(
        Time.now.year,
        Time.now.month,
        Time.now.day,
        Time.now.hour,
        Time.now.min, 0
        )
  end

  # 在社時間のフォーマット
  def working_time(started_at, finished_at)
    if started_at > finished_at # 翌日だった場合
      format("%.2f", (((finished_at.tomorrow - started_at) / 60) / 60.0)) #この計算結果は秒数で返ってくるため、秒数を2度60で割っている
    else
      format("%.2f", (((finished_at - started_at) / 60) / 60.0)) #この計算結果は秒数で返ってくるため、秒数を2度60で割っている
    end
  end
  
  # 在社時間の合計値
  def working_time_sum(seconds)
    format("%.2f", seconds / 60 / 60.0)
  end
  
  # 時間外時間
  def off_hours_time(id, overtime)
    end_time = overtime.endplans_time # endplans_timeを取得
    work_time = User.find(id).work_time_finish # usersテーブルのwork_time_finishを取得
    end_adjust = Time.new(end_time.year, end_time.month, end_time.day, end_time.hour, end_time.min, 0) # end_plans_timeを新しく作り調整
    work_adjust = Time.new(end_time.year, end_time.month, end_time.day, work_time.hour, work_time.min, 0) # work_time_finishを新しく作り調整(年月)
    if overtime.next_day == true  # 翌日だった場合
      format("%.2f", ((end_adjust.tomorrow - work_adjust) / 60) / 60)
    else
      format("%.2f", ((end_adjust - work_adjust) / 60) / 60)
    end
  end

  # 残業承認の表示
  def overtime_display(date)
    # supeior_userの名前だけ格納する配列nameを作成
    name = User.superior_user_list_non_self(session).map { |name| name[:name] }
    if name.index(date.over_order_id) # 配列nameの中にdate.over_order_idの申請者の名前があるかどうか
      "残業申請中：#{date.over_order_id}"
    elsif date.over_order_id == "承認"
      "残業承認済：#{date.over_order_status}"
    elsif date.over_order_id == "否認"
      "残業否認：#{date.over_order_status}"
    end
  end

  # 勤怠変更承認の表示
  def attendance_display(date)
    name = User.superior_user_list_non_self(session).map { |name| name[:name] }
    if name.index(date.attendance_order_id)
      "勤怠編集申請中：#{date.attendance_order_id}"
    elsif date.attendance_order_id == "承認"
      "勤怠編集承認済：#{date.attendance_order_status}"
    elsif date.attendance_order_id == "否認"
      "勤怠編集否認：#{date.attendance_order_status}"
    end
  end

  # 所属長承認のステータス
  def current_month_status(day)
    @user = User.find(params[:id])
    @attendance = @user.attendances.find_by(worked_on: day)
    name = User.superior_user_list_non_self(session).map { |name| name[:name] }
    if name.index(@attendance.month_order_id)
      "#{@attendance.month_order_id}に申請中"
    elsif @attendance.month_order_id == "承認" &&  @attendance.month_order_status.present?
      "#{@attendance.month_order_status}から承認済"
    elsif @attendance.month_order_id == "否認" &&  @attendance.month_order_status.present?
      "#{@attendance.month_order_status}から否認"
    else
      "未"
    end
  end
  
  # @first_dayの定義のリファクタリング (params[:first_day])
  def first_day(date)
    !date.nil? ? Date.parse(date) : Date.current.beginning_of_month
    # 元々は下記を使用していた
    # if params[:first_day].nil? # 時間管理表のlink_toでパラメータを受け取っているかどうか
    #   @first_day = Date.today.beginning_of_month
    # else
    #   @first_day = Date.parse(params[:first_day]) # params[:first_day]で受け取った値は文字列なので、parseメソッドでDateクラスオブジェクトに変えている
    # end
  end
  
  # @datesのリファクタリング
  def user_attendances_month_date
    @user.attendances.where('worked_on >= ? and worked_on <= ?', @first_day, @last_day).order('worked_on')
  end
  
  # 勤怠編集の更新時、不正な値がないか確認
  def attendances_invalid? # attendances_invalid?は真偽値（true, false）を返す
    attendances = true
    attendances_params.each do |id, item|
      if item[:attendance_order_id] != ""
        if item[:started_at].blank? && item[:finished_at].blank?
          next # nextは繰り返し処理の中で呼び出されると、その後の処理をスキップしつつ、繰り返し処理自体は続行。
        elsif item[:started_at].blank? || item[:finished_at].blank?
          attendances = false
          break # breakは単純に繰り返し処理を中断する。
        elsif item[:started_at] > item[:finished_at] && item[:next_day] == "true" # 翌日テェックがtrueの場合はOK
          break
        elsif item[:started_at] > item[:finished_at]
          attendances = false
          break
        end
      end
    end
    return attendances
  end
  
end

app/views/attendances/_attendance_info_modal.html.erb
<!-- モーダル・ダイアログ -->
<div class="modal fade" id="attendance-info-modal" tabindex="-1">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span>×</span></button>
			</div>
			
      <div class="modal-body">
        <%= form_for @user, url: update_attendance_info_attendance_path, method: :patch do |f| %>
        <% @title_name = Attendance.where(attendance_order_id: current_user.name).group_by(&:user_id) %>
          <% @title_name.each do |keys, values| %>
           <h4 class="modal-title" id="myModalLabel" style="text-align:center"><%= "【#{User.find(keys).name}からの勤怠変更申請】" %></h4>
            
              <table class= "table table-bordered table-striped table-condensed">
                <thead>
                  <tr>
                    <th rowspan="3" valign="bottom">日付</th>
                    <th rowspan="3" valign="bottom">曜日</th>
                    <th colspan="4">変更前</th>
                    <th colspan="4">変更後</th>
                    <th rowspan="3" valign="bottom">備考</th>
                    <th rowspan="3" valign="bottom">指示者確認㊞</th>
                    <th rowspan="3" valign="bottom">変更</th>
                    <th rowspan="3" valign="bottom">勤怠を確認する</th>
                  </tr>
                  
                  <tr>
                  	<th colspan="2">出社</th>
                  	<th colspan="2">退社</th>
                  	<th colspan="2">出社</th>
                  	<th colspan="2">退社</th>
                  </tr>
                  
                  <tr>
                  	<th>時</th>
                  	<th>分</th>
        						<th>時</th>
                  	<th>分</th>
                  	<th>時</th>
                  	<th>分</th>
                  	<th>時</th>
                  	<th>分</th>
                  </tr>
                </thead>
                
                <tbody>
                  <% values.each do |value| %>
                    <%= fields_for "attendances[]", value do |af| %>
                      <tr>
                        <!-- 日付 -->
                        <td><%= value.worked_on.to_s(:date) %></td>
                        <!-- 曜日 -->
                        <td><%= @week[value.worked_on.wday] %></td>
                        <!-- 変更前出社時間　時 -->
                        <td><%= value.started_at.to_s(:hour) if value.started_at.present? %></td>
                        <!-- 変更前出社時間　分 -->
                        <td><%= value.started_at.to_s(:min) if value.started_at.present? %></td>
                        <!-- 変更前退社時間　時 -->
                        <td><%= value.finished_at.to_s(:hour) if value.started_at.present? %></td>
                        <!-- 変更前退社時間　分 -->
                        <td><%= value.finished_at.to_s(:min) if value.started_at.present? %></td>
                        <!-- 変更後出社時間　時 -->
                        <td><%= value.started_at_after.to_s(:hour) %></td>
                        <!-- 変更後出社時間　分 -->
                        <td><%= value.started_at_after.to_s(:min) %></td>
                        <!-- 変更後退社時間　時 -->
                        <td><%= value.finished_at_after.to_s(:hour) %></td>
                        <!-- 変更後退社時間　分 -->
                        <td><%= value.finished_at_after.to_s(:min) %></td>
                        <!-- 備考 -->
                        <td><%= value.note %></td>
                        <!-- 指示者確認㊞ -->
                        <td><%= af.select :attendance_order_id, [["なし", "なし"],["申請中", "#{current_user.name}"],["承認", "承認"],["否認", "否認"]], :include_blank => true %></td>
                        <!-- 変更 -->
                        <td><%= af.check_box :agreement, {}, "true", "false" %></td>
                        <!-- 勤怠を確認する-->
                        <td><%= link_to "確認", user_path(id: keys, first_day: value.worked_on.beginning_of_month, modal: :attendance_info_modal), class: "btn btn-primary" %></td>
                      </tr>
                    <% end %> <!-- fields_for -->
                  <% end %> <!-- values.each -->
                </tbody>
              </table>
          <% end %>  <!-- each keys,values -->
             <%= f.submit "変更を送信する", class: "btn btn-primary btn-info-modal" %>
        <% end %> <!-- form_for --> 
      </div>
    </div> <!-- modal-content -->
  </div> <!-- modal-dialog -->
</div> <!-- modal fade -->

app/views/attendances/_month_info_modal.html.erb
<!-- モーダル・ダイアログ -->
<% provide :month_order_name, 'current_user.name' %>

<div class="modal fade" id="month-info-modal" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span>×</span></button>
			</div>
			
      <div class="modal-body">
        <%= form_for @user, url: update_month_info_attendance_path, method: :patch do |f| %>
        <% @title_name = Attendance.where(month_order_id: current_user.name).group_by(&:user_id) %>
          <% @title_name.each do |keys, values| %>
           <h4 class="modal-title" id="myModalLabel" style="text-align:center"><%= "【#{User.find(keys).name}からの１ヶ月分勤怠申請】" %></h4>
            
              <table class= "table table-bordered table-striped table-condensed">
                <thead>
                  <tr>
                    <th>月</th>
                    <th>指示者確認㊞</th>
                    <th>変更</th>
                    <th>勤怠を確認する</th>
                  </tr>
                </thead>
                  
                <tbody>
                  <% values.each do |value| %>
                    <%= fields_for "attendances[]", value do |af| %>
                      <tr>
                        <!-- 月 -->
                        <td><%= value.worked_on.month %>月</td>
                        <!-- 指示者確認㊞ -->
                        <td><%= af.select :month_order_id, [["なし", "なし"],["申請中", "#{current_user.name}"],["承認", "承認"],["否認", "否認"]], :include_blank => true %></td>
                        <!-- 変更 -->
                        <td><%= af.check_box :agreement, {}, "true", "false" %></td>
                        <!-- 勤怠を確認する -->
                        <td><%= link_to "確認", user_path(id: keys, first_day: value.worked_on.beginning_of_month, modal: :month_info_modal), class: "btn btn-primary" %></td>
                      </tr>
                    <% end %> <!-- fields_for -->
                  <% end %> <!-- each values -->
                </tbody>
              </table>
          <% end %>  <!-- each keys,values -->
             <%= f.submit "変更を送信する", class: "btn btn-primary btn-info-modal" %>
        <% end %> <!-- form_for --> 
      </div>
    </div> <!-- modal-content -->
  </div> <!-- modal-dialog -->
</div> <!-- modal fade -->

app/views/attendances/_overtime_info_modal.html.erb
<!-- モーダル・ダイアログ -->
<div class="modal fade" id="overtime-info-modal" tabindex="-1">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span>×</span></button>
			</div>
			
      <div class="modal-body">
        <%= form_for @user, url: update_overtime_info_attendance_path, method: :patch do |f| %>
        <% @title_name = Attendance.where(over_order_id: current_user.name).group_by(&:user_id) %>
          <% @title_name.each do |keys, values| %>
           <h4 class="modal-title" id="myModalLabel" style="text-align:center"><%= "【#{User.find(keys).name}からの残業申請】" %></h4>
            
              <table class= "table table-bordered table-striped table-condensed">
                <thead>
                  <tr>
                    <th>日付</th>
                    <th>曜日</th>
                    <th>終了予定時間</th>
                    <th>指定勤務終了時間</th>
                    <th>時間外時間</th>
                    <th>業務処理内容</th>
                    <th>指示者確認㊞</th>
                    <th>変更</th>
                    <th>勤怠を確認する</th>
                  </tr>
                </thead>
                
                <tbody>
                  <% values.each do |value| %>
                    <%= fields_for "attendances[]", value do |af| %>
                      <tr>
                        <!-- 日付 -->
                        <td><%= value.worked_on.to_s(:date) %></td>
                        <!-- 曜日 -->
                        <td><%= @week[value.worked_on.wday] %></td>
                        <!-- 終了予定時間 -->
                        <td><%= value.endplans_time.to_s(:time) %></td>
                        <!-- 指定勤務終了時間 -->
                        <td><%= format_basic_time(User.find(keys).work_time_finish) %></td>
                        <!-- 時間外時間 -->
                        <td><%= off_hours_time(keys, value) %></td>
                        <!-- 業務処理内容 -->
                        <td><%= value.business_contents %></td>
                        <!-- 指示者確認㊞ -->
                        <td><%= af.select :over_order_id, [["なし", "なし"],["申請中", "#{current_user.name}"],["承認", "承認"],["否認", "否認"]], :include_blank => true %></td>
                        <!-- 変更 -->
                        <td><%= af.check_box :agreement, {}, "true", "false" %></td>
                        <!-- 勤怠を確認する-->
                        <td><%= link_to "確認", user_path(id: keys, first_day: value.worked_on.beginning_of_month, modal: :overtime_info_modal), class: "btn btn-primary" %></td>
                      </tr>
                    <% end %> <!-- fields_for -->
                  <% end %> <!-- values.each -->
                </tbody>
              </table>
          <% end %>  <!-- each keys,values -->
             <%= f.submit "変更を送信する", class: "btn btn-primary btn-info-modal" %>
        <% end %> <!-- form_for --> 
      </div>
    </div> <!-- modal-content -->
  </div> <!-- modal-dialog -->
</div> <!-- modal fade -->

app/views/attendances/_overtime_modal.html.erb
<!-- モーダル・ダイアログ -->
<div class="modal fade" id="overtime-modal" tabindex="-1">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span>×</span></button>
				<h4 class="modal-title">【残業申請】</h4>
			</div>
			
      <div class="modal-body">
        <%= form_for @attendance, url: update_overtime_attendance_path(id: @user.id, first_day: @first_day), method: :patch do |f| %>

          <table class="txt1 table table-bordered table-striped table-condensed">
            <thead>
              <tr>
                <th>日付</th>
                <th>曜日</th>
                <th>終了予定時間</th>
                <th>翌日</th>
                <th>業務処理内容</th>
                <th>指示者確認㊞</th>
              </tr>
            </thead>
            
            <tbody>

                <tr>
                  <!-- 日付 -->
                  <td id="modal-date"></td>
                   
                  <!-- data-hidden_dateで取得した値を、コントローラーに飛ばす -->
                  <!--<= f.hidden_field :day, class: 'modal-hiddenDate' %>-->
                  <%= f.hidden_field :day, :value => "", :id => 'modal-hiddenDate' %>
                  
                  <!-- 曜日 -->
                  <td id="modal-youbi"></td>
                   <!--終了予定時間 -->
                  <td><%= f.time_field :endplans_time, class: 'form-control' %> </td>
                   <!--翌日チェック -->
                  <td><%= f.check_box :next_day, {}, "true", "false" %></td>
                   <!--業務処理内容 -->
                  <td><%= f.text_field :business_contents, class: 'form-controll' %></td>
                   <!--指示者確認㊞ -->
                  <td><%= f.collection_select :over_order_id, User.superior_user_list_non_self(session), :name, :name, :include_blank => true %></td>
                </tr>
                
            </tbody>
          </table>
          
          <%= f.submit "残業を申請する", class: "btn btn-primary btn-info-modal" %>
        <% end %><!-- form_for -->

      </div>
    </div> <!-- modal-content -->
  </div> <!-- modal-dialog -->
</div> <!-- modal fade -->


<script>
 $('#overtime-modal').on('show.bs.modal', function (event) { // ボタンがクリックされてモーダルが開いたらイベント発生
 　
  // クリックされたbuttonを取得
  var button = $(event.relatedTarget); 

  // 上記の中の、data-dateの値を取得
  var date = button.data('date'); 

  // クリックされているovertime-modal要素を取得
  var modal = $(this); 

  // overtime-modalの中のmodal-dateという要素を取得し、そこにdata-dateの値を入れる。これでクリックした日付の日付がモーダル内に入る
  modal.find('#modal-date').text(date); 
  
  // 上記同様にyoubiを取得
  var button = $(event.relatedTarget);
  var youbi = button.data('youbi');
  var modal =$(this);
  modal.find('#modal-youbi').text(youbi);

  // 日付をhiddenで送信したかったので上記と同様に処理
  var button = $(event.relatedTarget);
  var hidden_date = button.data('hidden_date');
  var modal =$(this);
  modal.find('#modal-hiddenDate').val(hidden_date);

 });
</script>

app/views/attendances/attendance_list.html.erb
<% provide(:title, '出勤社員一覧') %>

<h1>出勤社員一覧</h1>
  
<div>
  <table class = "table-bordered table-condensed table-striped">
    <thead>
      <tr>
        <td>社員番号</td>
        <td>名前</td>
      </tr>
    </thead>
    
    <tbody>
      <% @users.each do |user| %> <!-- userを繰り返し渡す -->
       <% user.attendances.each do |attendance| %> <!-- 受け取ったuser_idのattendaceを繰り返す -->
          <!-- 出社時間が存在かつ退勤時間がnilかつ日付が本日の場合、真 -->
          <% if attendance.started_at.present? && attendance.finished_at.nil? && attendance.worked_on == Date.today %>
          <tr>
            <!-- 社員番号 -->
            <td><%= user.code %></td>
            <!-- 名前 -->
            <td><%= user.name %></td>
          </tr>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>