config/routes.rb
Rails.application.routes.draw do
  
# static_pagesコントローラー
  # ルートページ
  root 'static_pages#home'
  
# usersコントローラー
  # 新規作成画面へ 
  get '/signup',    to: 'users#new'
  # 基本情報編集画面へ (/edit-basic-info/1という形式のURLでGETリクエストが送信出来るようになる)
  # このURLの記法だと_pathヘルパーが作成されないので、asオプションを使用することでbasic_info_pathメソッドが生成する
  get '/edit-basic-info', to: 'users#edit_basic_info', as: :basic_info 
  # 基本情報編集画面の更新処理
  patch 'update-basic-info', to: 'users#update_basic_info'
  
# sessionsコントローラー
  # ログイン画面へ
  get    '/login',  to: 'sessions#new'
  # セッションを作成&保存(ログイン状態になる)
  post   '/login',  to: 'sessions#create'
  # ログイン状態を破棄
  delete '/logout', to: 'sessions#destroy'
  
# users > attendancesコントローラー
  # 勤怠編集画面へ ( 何年何月の勤怠表示画面から遷移したかも判定し、編集画面の１ヶ月分の表示を合わせる必要があるため:dateを入れる )
  get 'user/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances
  # 勤怠編集の更新
  patch 'user/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  
# basesコントローラー
  # # 拠点情報ページへ
  # get 'bases/index', to: 'bases#index'
  # # 拠点情報の追加ページ
  # get 'bases/new', to: 'bases#new'
  # # 拠点情報の新規作成
  # post 'bases/create', to: 'bases#create', as: :bases
  # # 拠点情報の編集ページ
  # get 'bases/:id/edit', to: 'bases#edit', as: :edit_base
  # # 拠点情報の更新
  # patch 'bases/:id', to: 'bases#update', as: :base
  # # 拠点情報の削除
  # delete 'bases/:id', to: 'bases#destroy'
  
# baseリソース
  resources :bases do
  end
  
# usersリソース
  resources :users do

    
    member do
      patch  'update_index', as: :update_index # ユーザ一覧の更新
      get 'attendance_log', as: :attendance_log # 勤怠修正ログページ
    end
    
    # 勤怠情報を保存する
    resources :attendances, only: :create #リソースをネストしていることで/users/:user_id/attendanceというURLになる。
    
  end
  
  resources :attendances do
    collection do
      get 'attendance_list', as: :attendance_list # 出勤社員一覧ページ
      get 'csv_output', as: :csv_output # csv出力アクション
    end
    
    member do
      patch 'update_attendance_info', as: :update_attendance_info # 勤怠変更お知らせの更新
      patch 'update_overtime', as: :update_overtime # 残業申請
      patch 'update_overtime_info', as: :update_overtime_info # 残業申請お知らせの更新
      patch 'update_month', as: :update_month # １ヶ月分の勤怠申請
      patch 'update_month_info', as: :update_month_info # １ヶ月分の勤怠申請お知らせの更新
    end
  end

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">  <!--headerタグ 3つのクラスはBootStrapによって意味が与えられる -->
  <div class="container">  <!-- divタグ これもBootStrapによって意味が与えられる -->
  
    <% if !logged_in? %> <!-- 否定演算子なのでログインしていない場合true -->
      <%= link_to "勤怠システム", root_path, id: "logo" %>  <!-- classはページ内でなんども使えるが、idは一度しか使えない -->
    <% elsif current_user.admin? %>                                                  <!-- id:"logo"はオプションとなり、今回の場合はCSS idでlogoと指定している -->
      <%= link_to "勤怠システム", root_path, id: "logo" %>
      <div id="logo" style="color:red;">admin</div>
    <% elsif current_user.superior? %>
      <%= link_to "勤怠システム", current_user, id: "logo" %>
      <div id="logo" style="color:blue;">superior</div>
    <% else %>
      <%= link_to "勤怠システム", current_user, id: "logo" %>
      <div id="logo" style="color:green;">user</div>    
    <% end %>
    
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if !logged_in? %>
            <%= link_to "トップへ", root_path %>
          <% elsif current_user.admin? %>
            <%= link_to "トップへ", root_path %>
          <% else %>
            <%= link_to "トップへ", current_user %>
          <% end %>
        </li>
        <% if logged_in? %>  <!--sessionsヘルパーメソッド-->
          <% if current_user.admin? %> <!--adminかどうか-->
            <li><%= link_to "ユーザ一覧", users_path %></li>
            <li><%= link_to "出勤社員一覧", attendance_list_attendances_path %></li>
            <li><%= link_to "拠点情報の修正", bases_path %></li>
            <li><%= link_to "基本情報の更新", basic_info_path %></li>
          <% end %>
          <li class="dropdown">  <!-- Bootstrapクラスでレイアウト変更。有効化するため、JavaScriptとjQeryを読み込む指定をする(application.js)-->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "設定", edit_user_path(current_user) %></li>  <!-- 現在のユーザー情報が取得できるようcurrent_userを引数で渡している -->
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!-- Microsoft Internet Explorer(IE)のバージョンが９より小さい場合(if lt IE 9)のみ、囲まれている中の行を実行する -->
  
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>  <!-- 使用するHTMLのバージョンをブラウザに対して宣言している -->
<html>
  <head>
    <!-- full_title(カスタムヘルパー) -->
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- /スクリプトを読み込む -->
    <%= javascript_include_tag 'application' %>
    
    <%= render 'layouts/shim' %>  <!-- HTML shimがこの１行で済む -->
  </head>

  <body>
    <%= render 'layouts/header' %>  <!--headerがこの１行で済む -->
    <div class="container">
      <% flash.each do |message_type, message| %>  <!-- flashというオブジェクトを対象にflashハッシュキーとバリュー(keyとvalue)を繰り返し処理をする -->
        <div class="alert alert-<%= message_type %>"><%= message %></div>  <!-- alert- ~ のところはCSSのクラスが動的に変化する。例 alert-sucucess -->
      <% end %>
      <%= yield %>  <!-- 各viewの内容がここに挿入される -->
      <%= debug(params) if Rails.env.development? %> <!-- 開発環境でのみデバッグ情報を表示する -->
    </div>
  </body>
</html>